# Big Data -- Big file not added

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [3]:
# read in data
# initially reading in BIG data

cupid = pd.read_csv('data/okcupid_profiles.csv')

In [5]:
cupid.head(5)

,age,status,sex,orientation,body_type,diet,drinks,drugs,education,ethnicity,height,income,job,last_online,location,offspring,pets,religion,sign,smokes,speaks,essay0,essay1,essay2,essay3,essay4,essay5,essay6,essay7,essay8,essay9
0,22,single,m,straight,a little extra,strictly anything,socially,never,working on college/university,"asian, white",75.0,-1,transportation,2012-06-28-20-30,"south san francisco, california","doesn't have kids, but might want them",likes dogs and likes cats,agnosticism and very serious about it,gemini,sometimes,english,about me: i would love to think that i was so...,currently working as an international agent fo...,making people laugh. ranting about a good salt...,"the way i look. i am a six foot half asian, ha...","books: absurdistan, the republic, of mice and ...",food. water. cell phone. shelter.,duality and humorous things,trying to find someone to hang out with. i am ...,i am new to california and looking for someone...,you want to be swept off your feet! you are ti...
1,35,single,m,straight,average,mostly other,often,sometimes,working on space camp,white,70.0,80000,hospitality / travel,2012-06-29-21-41,"oakland, california","doesn't have kids, but might want them",likes dogs and likes cats,agnosticism but not too serious about it,cancer,no,"english (fluently), spanish (poorly), french (...",i am a chef: this is what that means. 1. i am ...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,i am die hard christopher moore fan. i don't r...,delicious porkness in all of its glories. my b...,NaN,NaN,i am very open and will share just about anyth...,NaN
2,38,available,m,straight,thin,anything,socially,NaN,graduated from masters program,NaN,68.0,-1,NaN,2012-06-27-09-10,"san francisco, california",NaN,has cats,NaN,pisces but it doesn&rsquo;t matter,no,"english, french, c++","i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,okay this is where the cultural matrix gets so...,movement conversation creation contemplation t...,NaN,viewing. listening. dancing. talking. drinking...,"when i was five years old, i was known as ""the...","you are bright, open, intense, silly, ironic, ..."
3,23,single,m,straight,thin,vegetarian,socially,NaN,working on college/university,white,71.0,20000,student,2012-06-28-14-22,"berkeley, california",doesn't want kids,likes cats,NaN,pisces,no,"english, german (poorly)",i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,"bataille, celine, beckett. . . lynch, jarmusch...",NaN,cats and german philosophy,NaN,NaN,you feel so inclined.
4,29,single,m,straight,athletic,NaN,socially,never,graduated from college/university,"asian, black, other",66.0,-1,artistic / musical / writer,2012-06-27-21-26,"san francisco, california",NaN,likes dogs and likes cats,NaN,aquarius,no,english,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at: http://bagsbrown....,i smile a lot and my inquisitive nature,"music: bands, rappers, musicians at the moment...",NaN,NaN,NaN,NaN,NaN

In [20]:
# holy moly big data

cupid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59946 entries, 0 to 59945
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          59946 non-null  int64
 1   status       59946 non-null  object
 2   sex          59946 non-null  object
 3   orientation  59946 non-null  object
 4   body_type    54650 non-null  object
 5   diet         35551 non-null  object
 6   drinks       56961 non-null  object
 7   drugs        45866 non-null  object
 8   education    53318 non-null  object
 9   ethnicity    54266 non-null  object
 10  height       59943 non-null  float64
 11  income       59946 non-null  int64
 12  job          51748 non-null  object
 13  last_online  59946 non-null  object
 14  location     59946 non-null  object
 15  offspring    24385 non-null  object
 16  pets         40025 non-null  object
 17  religion     39720 non-null  object
 18  sign         48890 non-null  object
 19  smokes       54434 non-null  object
 20  speaks       59896 non-null  object
 21  essay0       54458 non-null  object
 22  essay1       52374 non-null  object
 23  essay2       50308 non-null  object
 24  essay3       48470 non-null  object
 25  essay4       49409 non-null  object
 26  essay5       49096 non-null  object
 27  essay6       46175 non-null  object
 28  essay7       47495 non-null  object
 29  essay8       40721 non-null  object
 30  essay9       47343 non-null  object
dtypes: float64(1), int64(2), object(28)
memory usage: 14.2+ MB

In [21]:
# only 60k rows, not the worst..

cupid.shape

(59946, 31)

----

## Initial EDA w/ Large Data File

In [19]:
cupid.isna().sum()

age                0
status             0
sex                0
orientation        0
body_type       5296
diet           24395
drinks          2985
drugs          14080
education       6628
ethnicity       5680
height             3
income             0
job             8198
last_online        0
location           0
offspring      35561
pets           19921
religion       20226
sign           11056
smokes          5512
speaks            50
essay0          5488
essay1          7572
essay2          9638
essay3         11476
essay4         10537
essay5         10850
essay6         13771
essay7         12451
essay8         19225
essay9         12603
dtype: int64

In [9]:
cupid['offspring'].value_counts()

doesn't have kids                          7560
doesn't have kids, but might want them     3875
doesn't have kids, but wants them          3565
doesn't want kids                          2927
has kids                                   1883
has a kid                                  1881
doesn't have kids, and doesn't want any    1132
has kids, but doesn't want more             442
has a kid, but doesn't want more            275
has a kid, and might want more              231
wants kids                                  225
might want kids                             182
has kids, and might want more               115
has a kid, and wants more                    71
has kids, and wants more                     21
Name: offspring, dtype: int64

In [10]:
cupid['education'].value_counts()

graduated from college/university    23959
graduated from masters program        8961
working on college/university         5712
working on masters program            1683
graduated from two-year college       1531
graduated from high school            1428
graduated from ph.d program           1272
graduated from law school             1122
working on two-year college           1074
dropped out of college/university      995
working on ph.d program                983
college/university                     801
graduated from space camp              657
dropped out of space camp              523
graduated from med school              446
working on space camp                  445
working on law school                  269
two-year college                       222
working on med school                  212
dropped out of two-year college        191
dropped out of masters program         140
masters program                        136
dropped out of ph.d program            127
dropped out of high school             102
high school                             96
working on high school                  87
space camp                              58
ph.d program                            26
law school                              19
dropped out of law school               18
dropped out of med school               12
med school                              11
Name: education, dtype: int64

In [16]:
cupid['sex'].value_counts()

m    35829
f    24117
Name: sex, dtype: int64

In [17]:
cupid['age'].value_counts()

26     3724
27     3685
28     3583
25     3531
29     3295
24     3242
30     3149
31     2735
23     2592
32     2587
33     2206
22     1934
34     1902
35     1755
36     1583
37     1427
38     1330
21     1282
39     1172
42     1072
40     1030
41      980
20      953
43      858
44      708
45      643
19      611
46      578
47      529
48      481
49      459
50      437
51      350
52      344
18      309
56      271
54      267
55      265
57      256
53      252
59      221
58      197
60      195
61      176
62      167
63      138
64      113
65      109
66      105
67       66
68       59
69       31
109       1
110       1
Name: age, dtype: int64

In [18]:
cupid['body_type'].value_counts()

average           14652
fit               12711
athletic          11819
thin               4711
curvy              3924
a little extra     2629
skinny             1777
full figured       1009
overweight          444
jacked              421
used up             355
rather not say      198
Name: body_type, dtype: int64

In [25]:
cupid['sign'].value_counts()

gemini and it&rsquo;s fun to think about         1782
scorpio and it&rsquo;s fun to think about        1772
leo and it&rsquo;s fun to think about            1692
libra and it&rsquo;s fun to think about          1649
taurus and it&rsquo;s fun to think about         1640
cancer and it&rsquo;s fun to think about         1597
pisces and it&rsquo;s fun to think about         1592
sagittarius and it&rsquo;s fun to think about    1583
virgo and it&rsquo;s fun to think about          1574
aries and it&rsquo;s fun to think about          1573
aquarius and it&rsquo;s fun to think about       1503
virgo but it doesn&rsquo;t matter                1497
leo but it doesn&rsquo;t matter                  1457
cancer but it doesn&rsquo;t matter               1454
gemini but it doesn&rsquo;t matter               1453
taurus but it doesn&rsquo;t matter               1450
libra but it doesn&rsquo;t matter                1408
aquarius but it doesn&rsquo;t matter             1408
capricorn and it&rsquo;s fun to think about      1376
sagittarius but it doesn&rsquo;t matter          1375
aries but it doesn&rsquo;t matter                1373
capricorn but it doesn&rsquo;t matter            1319
pisces but it doesn&rsquo;t matter               1300
scorpio but it doesn&rsquo;t matter              1264
leo                                              1159
libra                                            1098
cancer                                           1092
virgo                                            1029
scorpio                                          1020
gemini                                           1013
taurus                                           1001
aries                                             996
pisces                                            992
aquarius                                          954
sagittarius                                       937
capricorn                                         833
scorpio and it matters a lot                       78
leo and it matters a lot                           66
aquarius and it matters a lot                      63
cancer and it matters a lot                        63
gemini and it matters a lot                        62
pisces and it matters a lot                        62
libra and it matters a lot                         52
taurus and it matters a lot                        49
sagittarius and it matters a lot                   47
aries and it matters a lot                         47
capricorn and it matters a lot                     45
virgo and it matters a lot                         41
Name: sign, dtype: int64

In [55]:
# drop rows where location != california

sum(cupid[cupid['location'].str.contains('california') == False]['location'].value_counts())

91

In [33]:
# group by what pet they like (likes/has dogs; likes/has cats) OR dislikes/no pets

cupid['pets'].value_counts()

likes dogs and likes cats          14814
likes dogs                          7224
likes dogs and has cats             4313
has dogs                            4134
has dogs and likes cats             2333
likes dogs and dislikes cats        2029
has dogs and has cats               1474
has cats                            1406
likes cats                          1063
has dogs and dislikes cats           552
dislikes dogs and likes cats         240
dislikes dogs and dislikes cats      196
dislikes cats                        122
dislikes dogs and has cats            81
dislikes dogs                         44
Name: pets, dtype: int64

In [56]:
# group by "laughing about it" or "not too serious about it" AS "doesn't matter"
# group by "somewhat serious about it" or "serious about it" AS "matters"
# all other values -- group by "matters"

cupid['religion'].value_counts()

agnosticism                                   2724
other                                         2691
agnosticism but not too serious about it      2636
agnosticism and laughing about it             2496
catholicism but not too serious about it      2318
atheism                                       2175
other and laughing about it                   2119
atheism and laughing about it                 2074
christianity                                  1957
christianity but not too serious about it     1952
other but not too serious about it            1554
judaism but not too serious about it          1517
atheism but not too serious about it          1318
catholicism                                   1064
christianity and somewhat serious about it     927
atheism and somewhat serious about it          848
other and somewhat serious about it            846
catholicism and laughing about it              726
judaism and laughing about it                  681
buddhism but not too serious about it          650
agnosticism and somewhat serious about it      642
judaism                                        612
christianity and very serious about it         578
atheism and very serious about it              570
catholicism and somewhat serious about it      548
other and very serious about it                533
buddhism and laughing about it                 466
buddhism                                       403
christianity and laughing about it             373
buddhism and somewhat serious about it         359
agnosticism and very serious about it          314
judaism and somewhat serious about it          266
hinduism but not too serious about it          227
hinduism                                       107
catholicism and very serious about it          102
buddhism and very serious about it              70
hinduism and somewhat serious about it          58
islam                                           48
hinduism and laughing about it                  44
islam but not too serious about it              40
islam and somewhat serious about it             22
judaism and very serious about it               22
islam and laughing about it                     16
hinduism and very serious about it              14
islam and very serious about it                 13
Name: religion, dtype: int64

In [57]:
# target variable?

cupid['orientation'].value_counts()

straight    51606
gay          5573
bisexual     2767
Name: orientation, dtype: int64

In [58]:
cupid['speaks'].value_counts()

english                                                                                     21828
english (fluently)                                                                           6628
english (fluently), spanish (poorly)                                                         2059
english (fluently), spanish (okay)                                                           1917
english (fluently), spanish (fluently)                                                       1288
                                                                                            ...
english (fluently), spanish (fluently), italian (okay), french (poorly), slovak (poorly)        1
english, tagalog (fluently), spanish (okay), farsi (poorly)                                     1
english (fluently), arabic (poorly), spanish (okay), japanese (poorly)                          1
english (fluently), spanish (fluently), french (fluently), italian (fluently)                   1
english (fluently), spanish (okay), italian (poorly), hebrew (poorly), latin (poorly)           1
Name: speaks, Length: 7647, dtype: int64

In [59]:
# look at responses?

cupid.iloc[:, 22:]

,essay1,essay2,essay3,essay4,essay5,essay6,essay7,essay8,essay9
0,currently working as an international agent fo...,making people laugh. ranting about a good salt...,"the way i look. i am a six foot half asian, ha...","books: absurdistan, the republic, of mice and ...",food. water. cell phone. shelter.,duality and humorous things,trying to find someone to hang out with. i am ...,i am new to california and looking for someone...,you want to be swept off your feet! you are ti...
1,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,i am die hard christopher moore fan. i don't r...,delicious porkness in all of its glories. my b...,NaN,NaN,i am very open and will share just about anyth...,NaN
2,"i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,okay this is where the cultural matrix gets so...,movement conversation creation contemplation t...,NaN,viewing. listening. dancing. talking. drinking...,"when i was five years old, i was known as ""the...","you are bright, open, intense, silly, ironic, ..."
3,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,"bataille, celine, beckett. . . lynch, jarmusch...",NaN,cats and german philosophy,NaN,NaN,you feel so inclined.
4,work work work work + play,creating imagery to look at: http://bagsbrown....,i smile a lot and my inquisitive nature,"music: bands, rappers, musicians at the moment...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
59941,the happiest times have been when life came to...,i make an outstanding osso bucco. i am also ve...,"i am told that people notice my smile, eyes an...",i am an avid movie watcher and follow the broa...,"my family, my dog, italy, words and music!",writing my book.,"running with my dog, finishing up the work wee...",i have a dream to sing at the alconquin in nyc...,you are seeking a long term connection of shar...
59942,currently finishing school for film production...,"filmmaking, photography, graphic design, web d...","dude, i don't know.","movies: hook (the greatest adventure ever!), g...",iphone contact lenses headphones camera tv rem...,i do most of my thinking on the bus to/from wo...,"bringin' home bacon, or drinking and shakin'!",when i was 18 i got a tattoo of waldo somewher...,meh if you made it this far you might as well.
59943,"i'm a civil engineer, who enjoys helping the c...",- looking at things objectively - getting thin...,i'm quiet until i get used to the environment ...,"last book: ""game change"". movies: bourne serie...",- iphone - friends and family - internet - bay...,"aside from work, how to improve my home.",out enjoying friendly conversation over dinner.,please let me think about this more.,we have similar interests.
59944,"following my dreams... ""you got a dream... you...",listening,it used to be the hair until i mowed it off bu...,where to begin musically: right now i listen t...,"music, family, friends, a basketball, hoop, so...",what can i do to make someone chuckle....,what i would do on any other day. everydays a ...,i like walking around in other people's house ...,you are interested and interesting...
59945,i work with elderly people (psychotherapy and ...,i'm a great bullshitter. i don't know what it ...,"either that i am funny/sarcastic, or that i am...","i just read the help by kathryn stockett, sooo...",1. family & friends & other humans - interacti...,"sex, myself, other people, how amazing everyth...","out at happy hour with my friends, running int...",i wish i could cry like holly hunter in broadc...,"if you have a back-bone, an opinion, a sense o..."

In [60]:
cupid.iloc[:, 22:].dropna()

,essay1,essay2,essay3,essay4,essay5,essay6,essay7,essay8,essay9
0,currently working as an international agent fo...,making people laugh. ranting about a good salt...,"the way i look. i am a six foot half asian, ha...","books: absurdistan, the republic, of mice and ...",food. water. cell phone. shelter.,duality and humorous things,trying to find someone to hang out with. i am ...,i am new to california and looking for someone...,you want to be swept off your feet! you are ti...
5,building awesome stuff. figuring out what's im...,imagining random shit. laughing at aforementio...,i have a big smile. i also get asked if i'm we...,"books: to kill a mockingbird, lord of the ring...","like everyone else, i love my friends and fami...",what my contribution to the world is going to ...,out with my friends!,i cried on my first day at school because a bi...,you're awesome.
9,i have an apartment. i like to explore and che...,i'm good at finding creative solutions to prob...,i'm short,i like some tv. i love summer heights high and...,"music, my guitar contrast good food my bike my...",you should,send a message,and say hi.,you can rock the bells
10,i have three jobs. i've been doing sound and l...,"hugging, kissing, laughing, motivating people,...",my huge goofy smile,"i'm constantly reading, i read at what my frie...",family friends food women music reading,"snowboarding, food, women, goofy nerd stuff, a...",having dinner and drinks with friends and/or w...,i used to wish for a jetpack when blowing out ...,you are a complex woman with healthy self-este...
11,i'm currently the youngest member on an intern...,i'm really good at a little bit of everything....,"the way i dress. some days it's hats, other da...",books = yes. avid reader. moves = eternal suns...,"guitar - even if i don't play it all the time,...",a little bit of everything. but mostly social ...,hanging out with a small group of friends--sta...,i'm picky when it comes to dating. i know what...,"if you know who you are, who you want, where y..."
...,...,...,...,...,...,...,...,...,...
59941,the happiest times have been when life came to...,i make an outstanding osso bucco. i am also ve...,"i am told that people notice my smile, eyes an...",i am an avid movie watcher and follow the broa...,"my family, my dog, italy, words and music!",writing my book.,"running with my dog, finishing up the work wee...",i have a dream to sing at the alconquin in nyc...,you are seeking a long term connection of shar...
59942,currently finishing school for film production...,"filmmaking, photography, graphic design, web d...","dude, i don't know.","movies: hook (the greatest adventure ever!), g...",iphone contact lenses headphones camera tv rem...,i do most of my thinking on the bus to/from wo...,"bringin' home bacon, or drinking and shakin'!",when i was 18 i got a tattoo of waldo somewher...,meh if you made it this far you might as well.
59943,"i'm a civil engineer, who enjoys helping the c...",- looking at things objectively - getting thin...,i'm quiet until i get used to the environment ...,"last book: ""game change"". movies: bourne serie...",- iphone - friends and family - internet - bay...,"aside from work, how to improve my home.",out enjoying friendly conversation over dinner.,please let me think about this more.,we have similar interests.
59944,"following my dreams... ""you got a dream... you...",listening,it used to be the hair until i mowed it off bu...,where to begin musically: right now i listen t...,"music, family, friends, a basketball, hoop, so...",what can i do to make someone chuckle....,what i would do on any other day. everydays a ...,i like walking around in other people's house ...,you are interested and interesting...
59945,i work with elderly people (psychotherapy and ...,i'm a great bullshitter. i don't know what it ...,"either that i am funny/sarcastic, or that i am...","i just read the help by kathryn stockett, sooo...",1. family & friends & other humans - interacti...,"sex, myself, other people, how amazing everyth...","out at happy hour with my friends, running int...",i wish i could cry like holly hunter in broadc...,"if you have a back-bone, an opinion, a sense o..."

----

## Make Smaller File

In [22]:
# pickle whole file, including essay columns? -- wayy too large still
# large file not saved

cupid.to_pickle('data/cupid.pkl')

In [27]:
cupid_check = pd.read_pickle('data/cupid.pkl')

In [28]:
cupid_check.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59946 entries, 0 to 59945
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          59946 non-null  int64
 1   status       59946 non-null  object
 2   sex          59946 non-null  object
 3   orientation  59946 non-null  object
 4   body_type    54650 non-null  object
 5   diet         35551 non-null  object
 6   drinks       56961 non-null  object
 7   drugs        45866 non-null  object
 8   education    53318 non-null  object
 9   ethnicity    54266 non-null  object
 10  height       59943 non-null  float64
 11  income       59946 non-null  int64
 12  job          51748 non-null  object
 13  last_online  59946 non-null  object
 14  location     59946 non-null  object
 15  offspring    24385 non-null  object
 16  pets         40025 non-null  object
 17  religion     39720 non-null  object
 18  sign         48890 non-null  object
 19  smokes       54434 non-null  object
 20  speaks       59896 non-null  object
 21  essay0       54458 non-null  object
 22  essay1       52374 non-null  object
 23  essay2       50308 non-null  object
 24  essay3       48470 non-null  object
 25  essay4       49409 non-null  object
 26  essay5       49096 non-null  object
 27  essay6       46175 non-null  object
 28  essay7       47495 non-null  object
 29  essay8       40721 non-null  object
 30  essay9       47343 non-null  object
dtypes: float64(1), int64(2), object(28)
memory usage: 14.2+ MB

In [5]:
# drop essay columns
cupid_subset = cupid.iloc[:,:21]

In [6]:
cupid_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59946 entries, 0 to 59945
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          59946 non-null  int64
 1   status       59946 non-null  object
 2   sex          59946 non-null  object
 3   orientation  59946 non-null  object
 4   body_type    54650 non-null  object
 5   diet         35551 non-null  object
 6   drinks       56961 non-null  object
 7   drugs        45866 non-null  object
 8   education    53318 non-null  object
 9   ethnicity    54266 non-null  object
 10  height       59943 non-null  float64
 11  income       59946 non-null  int64
 12  job          51748 non-null  object
 13  last_online  59946 non-null  object
 14  location     59946 non-null  object
 15  offspring    24385 non-null  object
 16  pets         40025 non-null  object
 17  religion     39720 non-null  object
 18  sign         48890 non-null  object
 19  smokes       54434 non-null  object
 20  speaks       59896 non-null  object
dtypes: float64(1), int64(2), object(18)
memory usage: 9.6+ MB

In [12]:
# change object type to category
# referenced https://git.generalassemb.ly/DSI-322/7.01-big-data/blob/master/big-data-memory-post-class.ipynb

cat_cols = cupid_subset.drop(columns = 'height').columns
cupid_subset[cat_cols] = cupid_subset[cat_cols].astype('category')

In [13]:
cupid_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59946 entries, 0 to 59945
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          59946 non-null  category
 1   status       59946 non-null  category
 2   sex          59946 non-null  category
 3   orientation  59946 non-null  category
 4   body_type    54650 non-null  category
 5   diet         35551 non-null  category
 6   drinks       56961 non-null  category
 7   drugs        45866 non-null  category
 8   education    53318 non-null  category
 9   ethnicity    54266 non-null  category
 10  height       59943 non-null  float64
 11  income       59946 non-null  category
 12  job          51748 non-null  category
 13  last_online  59946 non-null  category
 14  location     59946 non-null  category
 15  offspring    24385 non-null  category
 16  pets         40025 non-null  category
 17  religion     39720 non-null  category
 18  sign         48890 non-null  category
 19  smokes       54434 non-null  category
 20  speaks       59896 non-null  category
dtypes: category(20), float64(1)
memory usage: 3.4 MB

In [39]:
cupid_subset['status'].value_counts()

single            55697
seeing someone     2064
available          1865
married             310
unknown              10
Name: status, dtype: int64

In [52]:
# drop columns discriminating columns (i.e. ethnicity, height), unnecessary columns ('last_online', 'speaks'), and odd columns that had weird values ('income', 'job')

cupid_subset.drop(columns = ['height', 'ethnicity', 'job', 'last_online', 'speaks', 'income'],inplace = True)

In [55]:
cupid_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59946 entries, 0 to 59945
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          59946 non-null  category
 1   status       59946 non-null  category
 2   sex          59946 non-null  category
 3   orientation  59946 non-null  category
 4   body_type    54650 non-null  category
 5   diet         35551 non-null  category
 6   drinks       56961 non-null  category
 7   drugs        45866 non-null  category
 8   education    53318 non-null  category
 9   location     59946 non-null  category
 10  offspring    24385 non-null  category
 11  pets         40025 non-null  category
 12  religion     39720 non-null  category
 13  sign         48890 non-null  category
 14  smokes       54434 non-null  category
dtypes: category(15)
memory usage: 956.4 KB

In [57]:
cupid_subset.to_pickle('data/subset_cupid.pkl')

In [58]:
cupid_subset_check = pd.read_pickle('data/subset_cupid.pkl')

In [59]:
cupid_subset_check.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59946 entries, 0 to 59945
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          59946 non-null  category
 1   status       59946 non-null  category
 2   sex          59946 non-null  category
 3   orientation  59946 non-null  category
 4   body_type    54650 non-null  category
 5   diet         35551 non-null  category
 6   drinks       56961 non-null  category
 7   drugs        45866 non-null  category
 8   education    53318 non-null  category
 9   location     59946 non-null  category
 10  offspring    24385 non-null  category
 11  pets         40025 non-null  category
 12  religion     39720 non-null  category
 13  sign         48890 non-null  category
 14  smokes       54434 non-null  category
dtypes: category(15)
memory usage: 940.4 KB

In [ ]:
# grab only single / available people

# cupid_subset_check[(cupid_subset_check['status'] == 'single') | (cupid_subset_check['status'] == 'available')]